# Generated by Django 4.0.6 on 2022-07-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationstop',
            name='time_to_next_station',
            field=models.DurationField(),
        ),
    ]
